एक Data Analyst का बड़ा हिस्सा यही होता है:
Analysis करने से पहले data को trustworthy बनाना।

In [1]:
# Data Cleaning क्यों जरूरी है?

मान लो किसी manufacturing dataset में:

Production = 1000
Defects = 50
Defect Rate = 5%

लेकिन अगर 200 production records missing हैं, तो हमारा defect rate गलत हो सकता है।

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Pandas में missing value commonly NaN के रूप में दिखाई देती है।

In [3]:
# Missing Values Detect करना
tips.isnull() # यह हर cell के लिए True False देगा। लेकिन यह पूरा DataFrame बहुत बड़ा हो सकता है।

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [4]:
tips.isnull().sum()
# यह हर column में missing values की count देगा।

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

isna() और isnull() दोनों practically equivalent हैं
दोनों use कर सकते हो।
मैं recommend करूंगा कि दोनों को पहचानो, लेकिन एक consistent style रखो।

In [5]:
# 7. Missing Percentage

सिर्फ count जानना काफी नहीं है।

मान लो:

Column A → 10 missing
Column B → 500 missing

लेकिन अगर:

Column A → 100 rows
Column B → 100,000 rows

तो situation अलग है।

इसलिए missing percentage निकालना useful है:

In [6]:
missing_pct = tips.isnull().mean() * 100
missing_pct

total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

In [7]:
# Complete Missing Value Report
missing_report = pd.DataFrame({
    "missing_count": tips.isnull().sum(),
    "missing_percentage": tips.isnull().mean() * 100})

missing_report

            missing_count  missing_percentage
total_bill              0                 0.0
tip                     0                 0.0
sex                     0                 0.0
smoker                  0                 0.0
day                     0                 0.0
time                    0                 0.0
size                    0                 0.0

In [8]:
# Practice Dataset बनाते हैं
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D", "E"],
    "Age": [25, 30, np.nan, 40, 35],
    "Salary": [30000, np.nan, 40000, 50000, np.nan],
    "Department": ["QA", "Production", "QA", "Production", "QA"]})

df

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
2        C   NaN  40000.0          QA
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

In [9]:
df.isnull().sum()

Employee      0
Age           1
Salary        2
Department    0
dtype: int64

In [10]:
df.isnull().mean() * 100

Employee       0.0
Age           20.0
Salary        40.0
Department     0.0
dtype: float64

In [11]:
# मान लो हमें केवल वे rows चाहिए जिनमें Age missing है।
df[df["Age"].isnull()]

  Employee  Age   Salary Department
2        C  NaN  40000.0         QA

In [12]:
# Non-Missing Rows
df[df["Age"].notnull()]

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

In [13]:
df[df["Age"].notna()]

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

In [14]:
# अगर किसी row में किसी भी column में missing value है
df[df.isnull().any(axis=1)]

  Employee   Age   Salary  Department
1        B  30.0      NaN  Production
2        C   NaN  40000.0          QA
4        E  35.0      NaN          QA

axis=1 का मतलब Row-wise check.

In [15]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [Employee, Age, Salary, Department]
Index: []

In [16]:
df.dropna()

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
3        D  40.0  50000.0  Production

यह missing value वाली rows remove करेगा।
लेकिन ध्यान दो: dropna() default रूप से नया DataFrame return करता है।
Original df automatically change नहीं होता।

In [17]:
clean_df = df.dropna()

In big DF, if 5% missing value, अगर आप df.dropna() करते हो, तो कई useful records भी हट सकते हैं।

इसलिए Missing value देखते ही dropna() नहीं लगाना चाहिए।
पहले समझो कि missing क्यों है।

In [18]:
# Specific Column पर dropna()
# अगर हमें सिर्फ Age missing rows हटानी हैं:
df.dropna(subset=["Age"])

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

इसका मतलब केवल उन rows को हटाओ जहाँ Age missing है।
Salary missing होने से row नहीं हटेगी।

In [19]:
# Multiple Columns पर dropna()
df.dropna(subset=["Age", "Salary"])

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
3        D  40.0  50000.0  Production

In [20]:
# अगर row के सभी values missing हों तभी remove करना हो:
df.dropna(how="all")

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
2        C   NaN  40000.0          QA
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

df["Age"].fillna(0)
क्या Age में 0 डालना logical है? Usually नहीं। इसलिए filling strategy data के meaning पर depend करती है।

mean_age = df["Age"].mean()
df["Age"].fillna(mean_age)

या directly:

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [21]:
# Mean कब Use करें?

Mean useful हो सकता है जब:

-Data approximately symmetric हो
-Extreme outliers कम हों
-Missing values random हों

लेकिन अगर data में strong outliers हैं, mean problematic हो सकता है।

In [22]:
# Median Imputation

median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

Median अक्सर बेहतर होता है जब data skewed हो या outliers मौजूद हों।

In [23]:
# Mode Imputation

Categorical variable में mean/median नहीं निकाला जा सकता।

यहाँ mode:
df["Department"].mode()

निकाल सकते हैं।

df["Department"].mode()[0] #First mode

In [24]:
# Forward Fill — ffill()
temperature = pd.Series([25, 26, np.nan, np.nan, 29])
temperature

0    25.0
1    26.0
2     NaN
3     NaN
4    29.0
dtype: float64

In [25]:
temperature.ffill()
# fills with previous value in forward direction

0    25.0
1    26.0
2    26.0
3    26.0
4    29.0
dtype: float64

In [26]:
temperature.bfill()

0    25.0
1    26.0
2    29.0
3    29.0
4    29.0
dtype: float64

In [27]:
# Duplicate Data
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
# View duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [Employee, Age, Salary, Department]
Index: []

In [30]:
# remove duplicates
df.drop_duplicates()

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
2        C  32.5  40000.0          QA
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

In [31]:
clean_df = df.drop_duplicates()

In [32]:
# Duplicate Based on Specific Columns
# मान लो employee name unique होना चाहिए

df.duplicated(subset=["Employee"])

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [33]:
df.drop_duplicates(
    subset=["Employee"])

  Employee   Age   Salary  Department
0        A  25.0  30000.0          QA
1        B  30.0      NaN  Production
2        C  32.5  40000.0          QA
3        D  40.0  50000.0  Production
4        E  35.0      NaN          QA

In [34]:
# Data Type Problems
df.dtypes

Employee       object
Age           float64
Salary        float64
Department     object
dtype: object

In [35]:
# in real world data, numerical values may come in form of string
df["Salary"].dtype

dtype('float64')

In [36]:
# 38. String को Numeric में Convert करना
df["Salary"] = pd.to_numeric(
    df["Salary"],
    errors="coerce")

errors="coerce" invalid values को NaN बना देगा।

# Date conversion 
# Real datasets में dates अक्सर strings होती हैं

df["Date"] = pd.to_datetime(df["Date"],errors="coerce")

df["Date"].dtype

In [37]:
# Invalid Values

Temperature
25
28
30
-500
31

Technically -500 numeric है। लेकिन domain-wise impossible हो सकता है। 
यही distinction important है:

Valid datatype ≠ Valid business value

In [38]:
# Business Validation
tips["total_bill"] < 0

# Check करेगा negative bills हैं या नहीं।

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [39]:
(tips["total_bill"] < 0).sum()

np.int64(0)

In [40]:
(tips["tip"] < 0).sum()

np.int64(0)

In both above codes 
अगर result non-zero है, तो investigation जरूरी है।

In [41]:
# Range Validation
# मान लो party size

tips["size"].describe()

count    244.000000
mean       2.569672
std        0.951100
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: size, dtype: float64

In [42]:
tips["size"] <= 0

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: size, Length: 244, dtype: bool

In [43]:
tips["size"].min()

1

Domain knowledge से decide करेंगे कि values realistic हैं या नहीं।

Important Concept — Missing Data को हमेशा Fill नहीं करना

मान लो:
Customer Income में 40% values missing हैं।
आप simply mean से fill कर देते हो।
अब क्या हुआ?

आपने artificially बहुत सारे records को same average income दे दिया।
इससे:
-variance बदल सकता है
-distribution बदल सकती है
-correlation बदल सकता है
-model performance प्रभावित हो सकती है
इसलिए Imputation is a modeling/analysis decision, not just a coding operation.

Missing Value Strategy

एक practical decision framework:

Missing %
      ↓
Low
 ├── Remove rows?
 └── Impute?

Moderate
 ├── Impute
 ├── Flag missingness
 └── Domain analysis

High
 ├── Is column important?
 ├── Can source data be recovered?
 └── Should column be removed?

लेकिन exact threshold जैसे 5%, 20%, 50% को universal rule मत मानना।

Context matters.

49. 🧠 Interview Questions
Q1. What is missing data?

जब किसी observation के लिए expected value उपलब्ध नहीं होती।

Q2. Difference between dropna() and fillna()?
dropna()
→ Missing records/values remove करता है

fillna()
→ Missing values replace करता है

Q3. Mean vs Median imputation?

Mean outliers से प्रभावित होता है; median ज्यादा robust होता है।

Q4. What is forward fill?

Previous valid observation से missing value fill करना।

Q6. How do you detect duplicate rows?
df.duplicated().sum()

Q7. How do you convert a column to numeric?
pd.to_numeric(
    df["column"],
    errors="coerce")

Q8. Should all missing values be removed?

No.
पहले missingness का reason, percentage, business importance और analysis impact समझना चाहिए।