In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [3]:
# 3. What is Data Transformation?

Creating another column with the help of another column values, often called derived features.

In [4]:
# Creating Calculated Columns
tips["tip_percentage"] = tips["tip"] / tips["total_bill"] * 100

In [5]:
tips[["total_bill", "tip", "tip_percentage"]].head()

   total_bill   tip  tip_percentage
0       16.99  1.01        5.944673
1       10.34  1.66       16.054159
2       21.01  3.50       16.658734
3       23.68  3.31       13.978041
4       24.59  3.61       14.680765

In [6]:
tips["tip_percentage"] = tips["tip_percentage"].round(2)

In [7]:
tips[["total_bill", "tip", "tip_percentage"]].head()

   total_bill   tip  tip_percentage
0       16.99  1.01            5.94
1       10.34  1.66           16.05
2       21.01  3.50           16.66
3       23.68  3.31           13.98
4       24.59  3.61           14.68

In [8]:
#Bill Per Person
tips["bill_per_person"] = tips["total_bill"] / tips["size"]

In [9]:
tips["bill_per_person"] = tips["bill_per_person"].round(2)
tips[["total_bill", "size", "bill_per_person"]].head()

   total_bill  size  bill_per_person
0       16.99     2             8.49
1       10.34     3             3.45
2       21.01     3             7.00
3       23.68     2            11.84
4       24.59     4             6.15

In [10]:
# 6. apply() — Transforming Values
def bill_category(bill):
    if bill > 30:
        return "High"
    else:
        return "Normal"

In [11]:
tips["bill_category"] = tips["total_bill"].apply(bill_category)

In [12]:
tips[["total_bill", "bill_category"]].head(10)

   total_bill bill_category
0       16.99        Normal
1       10.34        Normal
2       21.01        Normal
3       23.68        Normal
4       24.59        Normal
5       25.29        Normal
6        8.77        Normal
7       26.88        Normal
8       15.04        Normal
9       14.78        Normal

In [13]:
# 7. apply() with Lambda
tips["bill_category"] = tips["total_bill"].apply(
    lambda x: "High" if x > 30 else "Normal")

In [14]:
# apply() with Multiple Conditions
def classify_bill(x):
    if x < 15:
        return "Low"
    elif x <= 30:
        return "Medium"
    else:
        return "High"

In [15]:
tips["bill_category"] = tips["total_bill"].apply(classify_bill)

In [16]:
tips[["total_bill", "bill_category"]].head(5)

   total_bill bill_category
0       16.99        Medium
1       10.34           Low
2       21.01        Medium
3       23.68        Medium
4       24.59        Medium

In [17]:
# 9. apply() with axis=1
def tip_level(row):
    if row["tip_percentage"] >= 20:
        return "Excellent"
    elif row["tip_percentage"] >= 15:
        return "Good"
    else:
        return "Low"

tips["tip_level"] = tips.apply(tip_level, axis=1)

Why axis=1?
Because we want the function to process one complete row at a time.

In [18]:
# 10. map() — Mapping Values

map() is especially useful when you want to convert categories into another representation.

For example:
Male → 1
Female → 0

In [19]:
tips["sex_code"] = tips["sex"].map({
    "Male": 1,
    "Female": 0})

In [20]:
tips[["sex", "sex_code"]].head()

      sex sex_code
0  Female        0
1    Male        1
2    Male        1
3    Male        1
4  Female        0

In [21]:
# 11. map() vs apply()

map()
Best for element-by-element mapping, especially dictionary-based mapping.

In [22]:
tips["sex_code"] = tips["sex"].map({"Male": 1,"Female": 0})

In [23]:
# apply(), is More flexible.
tips["bill_category"] = tips["total_bill"].apply(
    lambda x: "High" if x > 30 else "Normal")

Simple memory trick
map = mapping
apply = applying a function

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
# replace()
# useful when you want to replace specific values.
tips["day_full"] = tips["day"].replace({
    "Thur": "Thursday",
    "Fri": "Friday",
    "Sat": "Saturday",
    "Sun": "Sunday"})

In [26]:
tips[["day", "day_full"]].head(2)

   day day_full
0  Sun   Sunday
1  Sun   Sunday

map() vs replace()
One important difference:

map() can produce NaN for values that aren't present in the mapping dictionary.

replace() leaves unmatched values unchanged.