In [1]:
# Data Analysis Bootcamp — Lesson 2

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

In [3]:
# tips.head()

What is a DataFrame?
- The entire tips table is called a DataFrame.
- Think of a DataFrame as an Excel worksheet.

In [4]:
type(tips)

pandas.core.frame.DataFrame

In [5]:
# 4. What is a Series?

In [6]:
tips["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [7]:
type(tips["total_bill"])

pandas.core.series.Series

> A single column of a DataFrame is generally a Series.

In [8]:
tips[["total_bill", "tip"]][0:3] #dataframe

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50

In [9]:
tips["total_bill"][0:4] #gives series

0    16.99
1    10.34
2    21.01
3    23.68
Name: total_bill, dtype: float64

In [10]:
# 6. Selecting One Column

There are two common ways.

    Square brackets-
    tips["total_bill"]
    
    Dot notation-
    tips.total_bill
    
    Both generally work,However prefer Square brackets method, because column names can contain spaces or special characters. 
    
    df["Customer Name"] works, whereas:
    df.Customer Name , doesn't.

In [11]:
# 7. Selecting Multiple Columns
# tips[["total_bill", "tip", "sex"]]

Notice the double brackets.
>Why?
The outer brackets select from the DataFrame, and the inner brackets contain the list of columns.
>tips[
    ["total_bill", "tip", "sex"]
], The result is still a DataFrame.

In [12]:
# 10. .iloc[]

>iloc means:
integer-location based selection
It selects rows/columns based on their position.

>tips.iloc[0], Python uses zero-based indexing.

>tips.iloc[1]

>tips.iloc[0:5]

13. Select Specific Rows
>tips.iloc[[0, 2, 4]]

In [13]:
# 14. .iloc[] — Rows and Columns Together

data.iloc[row_position, column_position] 
tips.iloc[0, 0], Row position = 0, Column position = 0
tips.iloc[0:5, 0:3]

In [14]:
# 16. .loc[], loc performs label-based selection.

- tips.loc[0], row whose index label is 0.
- tips.loc[:, ["total_bill", "tip"]], Select all rows & two columns.
- tips.loc[0, "tip"],Row label 0, column label "tip"

tips["total_bill"].mean()
tips["total_bill"].max()
tips["total_bill"].min()

### Data Analysis Bootcamp — Lesson 3

Now we move from “How do I access data?” to the much more important analyst question:
“Can I trust this data?”
A professional analyst should never start analysis or build a dashboard immediately after loading a dataset. First, we inspect the dataset and understand its quality.


tips.columns
tips.dtypes
tips.info()
df.info()

tips.describe()
-count, Number of non-missing observations.
-std,Standard deviation- It tells us about the spread/variability of the data.
-25%, First quartile (Q1),25% of observations are below this value.

In [15]:
# 7. Why info() Is So Important

You don't need to manually inspect every row. When we have a very large number of rows and columns, we don't need to inspect every element.  For missing values, duplicate values, etc.

In [16]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

> This gives us a statistical overview.

std
Standard deviation.It tells us about the spread/variability of the data.

min
Smallest value.

25%
First quartile (Q1).25% of observations are below this value.

50%
Median.50% of observations are below this value.

75%
Third quartile (Q3).

max
Largest value.

In [17]:
tips["total_bill"].mean(), tips["total_bill"].median()

(np.float64(19.78594262295082), 17.795)

Why are they not exactly the same?
Because the distribution isn't perfectly symmetric.
There are some relatively large bills that pull the mean upward.
This is why an analyst shouldn't blindly use the mean.

In [18]:
# 11. Check Missing Values

# tips.isnull()

This returns True or False for every cell. But that's too much information.
Instead:

In [19]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [20]:
# Why .isnull().sum() Works

creates a table of True and False.
Python treats:
True  = 1
False = 0 

tips.isnull().sum()
counts the missing values column by column.

In [21]:
tips.isnull().mean() * 100

total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

In [22]:
# Check Duplicate Rows

tips.duplicated()- tips.duplicated()
tips.duplicated().sum()

tips["sex"].unique()--Check Unique Values
tips["sex"].nunique()-- tips["sex"].nunique()
tips["sex"].value_counts()-- Frequency of Each Category in a column

In [23]:
# Check Every Column's Unique Values
for column in tips.columns:
    print(column, ":", tips[column].nunique())

total_bill : 229
tip : 123
sex : 2
smoker : 2
day : 4
time : 2
size : 6

In [24]:
tips["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

>This mindset is more important than memorizing syntax.

#### Data Analysis Bootcamp — Lesson 4
#### Data Filtering & Conditional Analysis with Pandas

In [25]:
tips["total_bill"] > 20

0      False
1      False
2       True
3       True
4       True
       ...
239     True
240     True
241     True
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [27]:
tips[tips["total_bill"] > 20][0:4]

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [29]:
tips[tips["sex"] == "Male"][0:4]

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4

In [30]:
tips[tips["sex"] != "Male"][0:4]

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [31]:
tips[tips["smoker"] == "Yes"][0:4]

    total_bill   tip   sex smoker  day    time  size
56       38.01  3.00  Male    Yes  Sat  Dinner     4
58       11.24  1.76  Male    Yes  Sat  Dinner     2
60       20.29  3.21  Male    Yes  Sat  Dinner     2
61       13.81  2.00  Male    Yes  Sat  Dinner     2

In [33]:
# Show all customers who visited on Sunday.
tips[tips["day"] == "Sun"][0:3]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [34]:
# How many customers visited on Sunday?
len(tips[tips["day"] == "Sun"])

76

In [35]:
(tips["day"] == "Sun").sum()

np.int64(76)

#### Multiple Conditions

In [39]:
# Customers whose bill is greater than $20 AND tip is greater than $3.
tips[(tips["total_bill"] > 20) & (tips["tip"] > 3)][0:4]

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [40]:
tips[(tips["sex"] == "Male") & (tips["smoker"] == "Yes")][0:4]

    total_bill   tip   sex smoker  day    time  size
56       38.01  3.00  Male    Yes  Sat  Dinner     4
58       11.24  1.76  Male    Yes  Sat  Dinner     2
60       20.29  3.21  Male    Yes  Sat  Dinner     2
61       13.81  2.00  Male    Yes  Sat  Dinner     2

In [41]:
tips[
    (tips["sex"] == "Male") |
    (tips["smoker"] == "Yes")
]

     total_bill   tip     sex smoker  day    time  size
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
5         25.29  4.71    Male     No  Sun  Dinner     4
6          8.77  2.00    Male     No  Sun  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[190 rows x 7 columns]

&  → AND
|  → OR
~  → NOT

tips[~(tips["smoker"] == "Yes")]

tips[tips["smoker"] == "No"]

In [42]:
# Multiple AND Conditions
tips[
    (tips["total_bill"] > 20) &
    (tips["tip"] > 3) &
    (tips["size"] >= 3)
]

     total_bill    tip     sex smoker   day    time  size
2         21.01   3.50    Male     No   Sun  Dinner     3
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
7         26.88   3.12    Male     No   Sun  Dinner     4
11        35.26   5.00  Female     No   Sun  Dinner     4
19        20.65   3.35    Male     No   Sat  Dinner     3
23        39.42   7.58    Male     No   Sat  Dinner     4
35        24.06   3.60    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
54        25.56   4.34    Male     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
65        20.08   3.15    Male     No   Sat  Dinner     3
77        27.20   4.00    Male     No  Thur   Lunch     4
85        34.83   5.17  Female     No  Thur   Lunch     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
112       38.07   4.00    Male     No   Sun  Dinner     3
114       25.71   4.00  Female     No   Sun  Dinner     3
116       29.93   5.07    Male     No   Sun  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
165       24.52   3.48    Male     No   Sun  Dinner     3
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
180       34.65   3.68    Male    Yes   Sun  Dinner     4
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
189       23.10   4.00    Male    Yes   Sun  Dinner     3
197       43.11   5.00  Female    Yes  Thur   Lunch     4
204       20.53   4.00    Male    Yes  Thur   Lunch     4
206       26.59   3.41    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
219       30.14   3.09  Female    Yes   Sat  Dinner     4
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [43]:
# Suppose we want customers who came on:Saturday OR Sunday
tips[
    (tips["day"] == "Sat") |
    (tips["day"] == "Sun")
]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [44]:
#  or
tips[tips["day"].isin(["Sat", "Sun"])]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [45]:
tips[tips["day"].isin(["Fri", "Sat", "Sun"])]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[182 rows x 7 columns]

In [46]:
# Day is NOT Friday or Saturday.
tips[~tips["day"].isin(["Fri", "Sat"])]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
204       20.53  4.00    Male    Yes  Thur   Lunch     4
205       16.47  3.23  Female    Yes  Thur   Lunch     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[138 rows x 7 columns]

Suppose हमें केवल:total_bill,tip, day
देखना है, लेकिन सिर्फ उन customers के लिए जिनका bill > $20 है.

In [47]:
tips.loc[
    tips["total_bill"] > 20,
    ["total_bill", "tip", "day"]
]

     total_bill   tip  day
2         21.01  3.50  Sun
3         23.68  3.31  Sun
4         24.59  3.61  Sun
5         25.29  4.71  Sun
7         26.88  3.12  Sun
..          ...   ...  ...
237       32.83  1.17  Sat
238       35.83  4.67  Sat
239       29.03  5.92  Sat
240       27.18  2.00  Sat
241       22.67  2.00  Sat

[97 rows x 3 columns]

In [48]:
# Show bills greater than $20, highest bill first.
tips[tips["total_bill"] > 20].sort_values("total_bill",ascending=False)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
156       48.17   5.00    Male     No   Sun  Dinner     6
182       45.35   3.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
21        20.29   2.75  Female     No   Sat  Dinner     2
60        20.29   3.21    Male    Yes   Sat  Dinner     2
131       20.27   2.83  Female     No  Thur   Lunch     2
68        20.23   2.01    Male     No   Sat  Dinner     2
65        20.08   3.15    Male     No   Sat  Dinner     3

[97 rows x 7 columns]